### ISSUE TITLE
Support multiple-tenant configurations

### ISSUE THREAD

**Issue by nmaludy** [StackStorm-Exchange/stackstorm-jenkins#3]
Currently this pack can only communicate with a single jenkins instance.

It would be great if it could be used to communicate with a number of instances, for example based on environment or tenant.

Some examples of this being done in other packs:

- [vsphere](https://github.com/StackStorm-Exchange/stackstorm-vsphere) supports multiple credentials in the configuration
- [activedirectory](https://github.com/StackStorm-Exchange/stackstorm-activedirectory) supports multiple credentials in the configuration AND the option to override those credentials and pass them in as parameters to an action (so it can be used via the CLI, or potentially dynamically from the k/v store)

**Comment by igcherkaev** [comment]
@nmaludy think we can close this issue?
