### ISSUE TITLE
Return from build_job is just queue_id - is there a better return possible?

### ISSUE THREAD

**Issue by j3p0uk** [StackStorm-Exchange/stackstorm-jenkins#6]
From looking up details on the queue_id returned by the python-jenkins build_job() function, it is a temporary ID that will be discarded from the main queue after about 5 mins from the job being scheduled.

This means that whilst the job is in the queue, the build details can be found by calling jenkins.get_queue_item(queue_id), but after that queue has had garbage collection performed, the build details can only be retrieved through looking for the relevant build that has the correct queue id, and for this you need to know the project.

Should the build_job action here wait for the job to be scheduled and return the actual build info?  Should it get the queue item and return that?  Both of these would still contain the queue_id, but would also have more context and enable easier lookup of the build after the action has completed.

**Comment by LindsayHill** [comment]
Resolved by #9
